"""
This type stub file was generated by pyright.
"""

from . import attributes, properties, strategies
from .query import Query
from .. import log

"""Dynamic collection API.

Dynamic collections act like Query() objects for read operations and support
basic add/delete mutation.

"""
@log.class_logger
@properties.RelationshipProperty.strategy_for(lazy="dynamic")
class DynaLoader(strategies.AbstractRelationshipLoader):
    def init_class_attribute(self, mapper):
        ...
    


class DynamicAttributeImpl(attributes.AttributeImpl):
    uses_objects = ...
    default_accepts_scalar_loader = ...
    supports_population = ...
    collection = ...
    dynamic = ...
    def __init__(self, class_, key, typecallable, dispatch, target_mapper, order_by, query_class=..., **kw) -> None:
        ...
    
    def get(self, state, dict_, passive=...):
        ...
    
    def get_collection(self, state, dict_, user_data=..., passive=...):
        ...
    
    def fire_append_event(self, state, dict_, value, initiator, collection_history=...):
        ...
    
    def fire_remove_event(self, state, dict_, value, initiator, collection_history=...):
        ...
    
    def set(self, state, dict_, value, initiator=..., passive=..., check_old=..., pop=..., _adapt=...):
        ...
    
    def delete(self, *args, **kwargs):
        ...
    
    def set_committed_value(self, state, dict_, value):
        ...
    
    def get_history(self, state, dict_, passive=...):
        ...
    
    def get_all_pending(self, state, dict_, passive=...):
        ...
    
    def append(self, state, dict_, value, initiator, passive=...):
        ...
    
    def remove(self, state, dict_, value, initiator, passive=...):
        ...
    
    def pop(self, state, dict_, value, initiator, passive=...):
        ...
    


class AppenderMixin(object):
    query_class = ...
    def __init__(self, attr, state) -> None:
        ...
    
    def session(self):
        ...
    
    session = ...
    def __iter__(self):
        ...
    
    def __getitem__(self, index):
        ...
    
    def count(self):
        ...
    
    def extend(self, iterator):
        ...
    
    def append(self, item):
        ...
    
    def remove(self, item):
        ...
    


class AppenderQuery(AppenderMixin, Query):
    """A dynamic query that supports basic collection storage operations."""
    ...


def mixin_user_query(cls):
    """Return a new class with AppenderQuery functionality layered over."""
    ...

class CollectionHistory(object):
    """Overrides AttributeHistory to receive append/remove events directly."""
    def __init__(self, attr, state, apply_to=...) -> None:
        ...
    
    @property
    def added_plus_unchanged(self):
        ...
    
    @property
    def all_items(self):
        ...
    
    def as_history(self):
        ...
    
    def indexed(self, index):
        ...
    
    def add_added(self, value):
        ...
    
    def add_removed(self, value):
        ...
    


