"""
This type stub file was generated by pyright.
"""

from ..sql import operators

class UnevaluatableError(Exception):
    ...


_straight_ops = set(getattr(operators, op) for op in ("add", "mul", "sub", "div", "mod", "truediv", "lt", "le", "ne", "gt", "ge", "eq"))
_notimplemented_ops = set(getattr(operators, op) for op in ("like_op", "notlike_op", "ilike_op", "notilike_op", "between_op", "in_op", "notin_op", "endswith_op", "concat_op"))
class EvaluatorCompiler(object):
    def __init__(self, target_cls=...) -> None:
        ...
    
    def process(self, clause):
        ...
    
    def visit_grouping(self, clause):
        ...
    
    def visit_null(self, clause):
        ...
    
    def visit_false(self, clause):
        ...
    
    def visit_true(self, clause):
        ...
    
    def visit_column(self, clause):
        ...
    
    def visit_clauselist(self, clause):
        ...
    
    def visit_binary(self, clause):
        ...
    
    def visit_unary(self, clause):
        ...
    
    def visit_bindparam(self, clause):
        ...
    


