"""
This type stub file was generated by pyright.
"""

from .util import decorator

class ConnectionKiller(object):
    def __init__(self) -> None:
        ...
    
    def add_engine(self, engine):
        ...
    
    def connect(self, dbapi_conn, con_record):
        ...
    
    def checkout(self, dbapi_con, con_record, con_proxy):
        ...
    
    def invalidate(self, dbapi_con, con_record, exception):
        ...
    
    def rollback_all(self):
        ...
    
    def close_all(self):
        ...
    
    def assert_all_closed(self):
        ...
    


testing_reaper = ConnectionKiller()
def drop_all_tables(metadata, bind):
    ...

@decorator
def assert_conns_closed(fn, *args, **kw):
    ...

@decorator
def rollback_open_connections(fn, *args, **kw):
    """Decorator that rolls back all open connections after fn execution."""
    ...

@decorator
def close_first(fn, *args, **kw):
    """Decorator that closes all connections before fn execution."""
    ...

@decorator
def close_open_connections(fn, *args, **kw):
    """Decorator that closes all connections after fn execution."""
    ...

def all_dialects(exclude=...):
    ...

class ReconnectFixture(object):
    def __init__(self, dbapi) -> None:
        ...
    
    def __getattr__(self, key):
        ...
    
    def connect(self, *args, **kwargs):
        ...
    
    def shutdown(self, stop=...):
        ...
    
    def restart(self):
        ...
    


def reconnecting_engine(url=..., options=...):
    ...

def testing_engine(url=..., options=...):
    """Produce an engine configured by --options with optional overrides."""
    ...

def mock_engine(dialect_name=...):
    """Provides a mocking engine based on the current testing.db.

    This is normally used to test DDL generation flow as emitted
    by an Engine.

    It should not be used in other cases, as assert_compile() and
    assert_sql_execution() are much better choices with fewer
    moving parts.

    """
    ...

class DBAPIProxyCursor(object):
    """Proxy a DBAPI cursor.

    Tests can provide subclasses of this to intercept
    DBAPI-level cursor operations.

    """
    def __init__(self, engine, conn, *args, **kwargs) -> None:
        ...
    
    def execute(self, stmt, parameters=..., **kw):
        ...
    
    def executemany(self, stmt, params, **kw):
        ...
    
    def __getattr__(self, key):
        ...
    


class DBAPIProxyConnection(object):
    """Proxy a DBAPI connection.

    Tests can provide subclasses of this to intercept
    DBAPI-level connection operations.

    """
    def __init__(self, engine, cursor_cls) -> None:
        ...
    
    def cursor(self, *args, **kwargs):
        ...
    
    def close(self):
        ...
    
    def __getattr__(self, key):
        ...
    


def proxying_engine(conn_cls=..., cursor_cls=...):
    """Produce an engine that provides proxy hooks for
    common methods.

    """
    ...

