[tool.poetry]
name = "muse_for_anything"
version = "0.1.0"
description = "A tool for managing Ontologies with Data."
authors = ["Fabian Bühler"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
flask = { extras = ["dotenv"], version = "^1.1.2" }
invoke = "^1.4.1"
Flask-JWT-Extended = "^3.24.1"
Flask-Cors = "^3.0.9"
Flask-SQLAlchemy = "^2.4.4"
Flask-Migrate = "^2.5.3"
flask-babel = "^2.0.0"
flask-smorest = "^0.25.0"
Flask-Static-Digest = "^0.1.3"
marshmallow-jsonschema = "^0.12.0"
jsonschema = "^3.2.0"
flask-oso = "^0.9.0"
bcrypt = "^3.2.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
pytest = "^6.1.1"
flake8-docstrings = "^1.5.0"
flake8-bugbear = "^20.1.4"
Sphinx = "^3.2.1"
tomlkit = "^0.7.0"
recommonmark = "^0.6.0"
sphinxcontrib-redoc = "^1.6.0"
sphinx-click = "^2.5.0"

[tool.poetry.scripts]
#flask = 'flask.cli:main'

[tool.black]
line-length = 90
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
reverse_relative = true
group_by_package = true
honor_noqa = true
atomic = true

[tool.sphinx]
copyright-year = 2020
enable-autodoc = true
enable-autosectionlabel = true
enable-markdown = true
enable-todo = true
# update gitignore if you want to edit docs/changelog.md manually!
include-changelog = true
# update gitignore if you want to edit docs/readme.md manually!
include-readme = true

[tool.sphinx.intersphinx-mapping]
python = ["https://docs.python.org/3"]

[tool.sphinx.recommonmark]
auto-toc-tree-section = "Contents"
enable-math = false
enable-inline-math = false
enable-eval-rst = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
