"""
This type stub file was generated by pyright.
"""

"""Topological sorting algorithms."""
def sort_as_subsets(tuples, allitems, deterministic_order=...):
    ...

def sort(tuples, allitems, deterministic_order=...):
    """sort the given list of items by dependency.

    'tuples' is a list of tuples representing a partial ordering.
    'deterministic_order' keeps items within a dependency tier in list order.
    """
    ...

def find_cycles(tuples, allitems):
    ...

