"""
This type stub file was generated by pyright.
"""

from sqlalchemy import types as sqltypes
from sqlalchemy.dialects.sybase.base import SybaseDialect, SybaseExecutionContext, SybaseSQLCompiler

"""
.. dialect:: sybase+pysybase
    :name: Python-Sybase
    :dbapi: Sybase
    :connectstring: sybase+pysybase://<username>:<password>@<dsn>/[database name]
    :url: http://python-sybase.sourceforge.net/

Unicode Support
---------------

The python-sybase driver does not appear to support non-ASCII strings of any
kind at this time.

"""
class _SybNumeric(sqltypes.Numeric):
    def result_processor(self, dialect, type_):
        ...
    


class SybaseExecutionContext_pysybase(SybaseExecutionContext):
    def set_ddl_autocommit(self, dbapi_connection, value):
        ...
    
    def pre_exec(self):
        ...
    


class SybaseSQLCompiler_pysybase(SybaseSQLCompiler):
    def bindparam_string(self, name, **kw):
        ...
    


class SybaseDialect_pysybase(SybaseDialect):
    driver = ...
    execution_ctx_cls = ...
    statement_compiler = ...
    colspecs = ...
    @classmethod
    def dbapi(cls):
        ...
    
    def create_connect_args(self, url):
        ...
    
    def do_executemany(self, cursor, statement, parameters, context=...):
        ...
    
    def is_disconnect(self, e, connection, cursor):
        ...
    


dialect = SybaseDialect_pysybase
