"""
This type stub file was generated by pyright.
"""

def connection_memoize(key):
    """Decorator, memoize a function in a connection.info stash.

    Only applicable to functions which take no arguments other than a
    connection.  The memo will be stored in ``connection.info[key]``.
    """
    ...

def py_fallback():
    ...

