"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping

class MultiDictProxy(Mapping):
    """
    A proxy object which wraps multidict types along with a matching schema
    Whenever a value is looked up, it is checked against the schema to see if
    there is a matching field where `is_multiple` is True. If there is, then
    the data should be loaded as a list or tuple.

    In all other cases, __getitem__ proxies directly to the input multidict.
    """
    def __init__(self, multidict, schema) -> None:
        ...
    
    def __getitem__(self, key):
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self):
        ...
    
    def __delitem__(self, key):
        ...
    
    def __setitem__(self, key, value):
        ...
    
    def __getattr__(self, name):
        ...
    
    def __iter__(self):
        ...
    
    def __contains__(self, x):
        ...
    
    def __len__(self):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    


